const brazilianStates = [
  { state: "Acre", abbrev: "AC" },
  { state: "Alagoas", abbrev: "AL" },
  { state: "Amapá", abbrev: "AP" },
  { state: "Amazonas", abbrev: "AM" },
  { state: "Bahia", abbrev: "BA" },
  { state: "Ceará", abbrev: "CE" },
  { state: "Distrito Federal", abbrev: "DF" },
  { state: "Espírito Santo", abbrev: "ES" },
  { state: "Goiás", abbrev: "GO" },
  { state: "Maranhão", abbrev: "MA" },
  { state: "Mato Grosso", abbrev: "MT" },
  { state: "Mato Grosso do Sul", abbrev: "MS" },
  { state: "Minas Gerais", abbrev: "MG" },
  { state: "Pará", abbrev: "PA" },
  { state: "Paraíba", abbrev: "PB" },
  { state: "Paraná", abbrev: "PR" },
  { state: "Pernambuco", abbrev: "PE" },
  { state: "Piauí", abbrev: "PI" },
  { state: "Rio de Janeiro", abbrev: "RJ" },
  { state: "Rio Grande do Norte", abbrev: "RN" },
  { state: "Rio Grande do Sul", abbrev: "RS" },
  { state: "Rondônia", abbrev: "RO" },
  { state: "Roraima", abbrev: "RR" },
  { state: "Santa Catarina", abbrev: "SC" },
  { state: "São Paulo", abbrev: "SP" },
  { state: "Sergipe", abbrev: "SE" },
  { state: "Tocantins", abbrev: "TO" },
];

export default brazilianStates;
